name: Main testing workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run nickwph/apple-provisioning-profile-action@v1
        uses: ./
        with:
          profile-base64: YXBwbGUtcHJvdmlzaW9uaW5nLXByb2ZpbGUtYWN0aW9u
      - name: Verify result
        run: |
          ACTUAL=$(cat ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision)
          EXPECTED="apple-provisioning-profile-action"
          [[ "$ACTUAL" = "$EXPECTED" ]] && exit 0 || exit 1
  test-with-file:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo YXBwbGUtcHJvdmlzaW9uaW5nLXByb2ZpbGUtYWN0aW9uLTI= > $RUNNER_TEMP/fake.mobileprovision
      - name: Run nickwph/apple-provisioning-profile-action@v1
        uses: ./
        with:
          profile-file: $RUNNER_TEMP/fake.mobileprovision
      - name: Verify result
        run: |
          ACTUAL=$(cat ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision)
          EXPECTED="apple-provisioning-profile-action-2"
          [[ "$ACTUAL" = "$EXPECTED" ]] && exit 0 || exit 1
  test-base64-override-file:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo YXBwbGUtcHJvdmlzaW9uaW5nLXByb2ZpbGUtYWN0aW9uLTI= > $RUNNER_TEMP/fake.mobileprovision
      - name: Run nickwph/apple-provisioning-profile-action@v1
        uses: ./
        with:
          profile-base64: YXBwbGUtcHJvdmlzaW9uaW5nLXByb2ZpbGUtYWN0aW9u
          profile-file: $RUNNER_TEMP/fake.mobileprovision
      - name: Verify result
        run: |
          ACTUAL=$(cat ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision)
          EXPECTED="apple-provisioning-profile-action"
          [[ "$ACTUAL" = "$EXPECTED" ]] && exit 0 || exit 1