name: Main testing workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run nickwph/apple-provisioning-profile-action@v1
        uses: ./
        with:
          profile-base64: ${{ secrets.PROFILE_BASE64 }}
  test-with-file:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run nickwph/apple-provisioning-profile-action@v1
        uses: ./
        with:
          profile-base64: ${{ secrets.PROFILE_BASE64 }}
      - run: |
          
  test-base64-override-file:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run nickwph/apple-provisioning-profile-action@v1
        uses: ./
        with:
          profile-base64: ${{ secrets.PROFILE_BASE64 }}